### ISSUE TITLE
Remove pre-filled amount 0.000 from send dialog and get rid of input field manipulation

### ISSUE THREAD

**Issue by bobanm** [hhanh00/zwallet#10]
The current behavior is quite confusing. You can't delete the pre-filled `0.000` value. If you tap at the very end of the amount value and enter digits `69`, you don't append those at the end to get `0.00069` as expected. Instead the last 2 zeros of the pre-filled amount change into the values you enter, and you end up with `0.069`.

To make things worse, there is a bug in how the input field formats number when adding digits in the middle. To reproduce:
1. Open Send dialog
2. Enter `2` at the beginning of the amount. It will correctly change the amount from `0.000` to `20.000`
3. Now move the cursor to the position **after** the decimal point and tap `5`.
4. You would expect the amount to change to `20.500` but instead you get `205.000`

**Comment by hhanh00** [comment]
It is modeled after a fixed point calculator. Cash registers work the same way. Since the number of decimals is constant, you type in the value without considering the 'dot'. Ex: 15.430 is entered by typing 15430. Basically, the input is in mzec.
