### ISSUE TITLE
"Balance in Fiat currency and Exchange Rate" not visible

### ISSUE THREAD

**Issue by cochinada** [hhanh00/zwallet#101]
### Subject of the issue
I cannot see the "Balance in Fiat currency and Exchange Rate" for my ZEC as the manual suggests.

### Your environment
* 1.4.1+469/95aec7b9
* Windows 10

### Steps to reproduce
I've just run ywallet for the 1st time and let it synchronize.
Note that I only have balance on transparent addresses.

### Expected behaviour
According to the manual I should see the Balance in Fiat currency and Exchange Rate below my current ZEC total.

### Actual behaviour
I only see my current ZEC total.and the black background where the other information should be visible.
I'm able to see the price of ZEC over time on the "wallet P&L# though.
![no balance](https://github.com/hhanh00/zwallet/assets/70335046/565c617d-49d1-4f48-967b-ffe4fbbe1fa7)
![wallet P L](https://github.com/hhanh00/zwallet/assets/70335046/ee4380e5-0206-434e-a062-3dff134dcf26)

**Comment by hhanh00** [comment]
It looks like our source of real time price is not available at the time. Coingecko has short outages. Historical prices are recorded and stored in the app. They are affected.
Try reopening the wallet at a later time.

Thanks,

**Comment by cochinada** [comment]
Thanks! After 2 days of blackness it now shows it all!
Funny you mention Coingecko because I was using a Power Query on excel for their API that stopped working since a few weeks ago. I gave up after many troubleshooting but I suspect it might be related with Cloudfare. I have no issues with Coimmarketcap though.
