### ISSUE TITLE
Snap (i.e. diversified) addresses

### ISSUE THREAD

**Issue by skironDotNet** [hhanh00/zwallet#108]
I went thru ZecWallet Lite (no longer maintained), Zingo, Nighthow, but YWallet on PC is the powerhouse, and the documentation is amazing, you are only one to let me understand how addresses are constructed.
I have issue, I wish to understand (please add to documentation for others?) how snap address is created. At first I thought it's just magic name for "give me next address" and that using keytool I could recover it, but I tried and it doesn't seem to work that way, so 
1. How to recover snap address using KeyTool, what's the derivation path?
2. How YWallet is keeping track of those to let say if I generate snap address, and reset the wallet, send the funds to this address, and then use seed to add the account (fresh start) how does YWallet know tho also include snap addresses in scanning, and how far does it go on it's own? If clicked 20 times on snap address, will how it will know to scan up to 20 snap addresses, it won't! so how to tell it to scan 20th snap address. I won't use the wallet that way, just want to understand what to expect   

Thank you, and great job!

**Comment by hhanh00** [comment]
Thanks for the kind words.
1. The derivation path is the same as the main address. All diversified addresses have the same secret key! This is why creating them does not increase synchronization time. You are free to use 1000000 snap addresses and your wallet will remain as fast as before.
2. YWallet does not keep track of any snap address. The scanning includes *every* snap address at no cost. There is only one scan done, unlike ZecWallet Lite which would require 20 scans in your example.

**Comment by skironDotNet** [comment]
Makes sense! Amazing!
but how is it possible then to generate different public key from same secret key? (trying to learn something new)
thanks!

**Comment by hhanh00** [comment]
It uses a different generator point which is included in the address. See https://www.youtube.com/watch?v=ygmBUjJgCVs

**Comment by skironDotNet** [comment]
Awesome work, great video. Thank you
