### ISSUE TITLE
Ability to set custom server before adding any account

### ISSUE THREAD

**Issue by skironDotNet** [hhanh00/zwallet#109]
Currently since the first screen is to add a new account, nothing can be done regarding settings, so the only way I found to set custom server before restoring my true wallet is to create dummy account, then go to settings setup custom server, then restore real wallet and delete the dummy account.

**Comment by hhanh00** [comment]
Another way to do that without having to create a dummy account:
- create a new account
- on the rescan dialog where it asks for the birth height/date, tap CANCEL
- change the server in the settings
- rescan

**Comment by skironDotNet** [comment]
Makes sense but what I meant is very first time run of the wallet, fresh install, then in order to recover a wallet using custom server dummy account is only work around. I guess it's ok, I did learn swipe left/right is to delete the account, but in case you are bored and I'm sure you are not, rather busy :) you could add settings screen available before adding very first account/wallet

**Comment by hhanh00** [comment]
The first time you run the wallet, you can still cancel the rescan.

**Comment by skironDotNet** [comment]
ah true, I can put lower b-day number to have enough time to pause the scan.
Up to you if you want to close this issue or keep. I still think it would be nice to set server before creating any account, but I don't need it, so you can keep it as mega low priority enhancement (and let other to read it as wall), or you can close it.
Thanks!

**Comment by hhanh00** [comment]
Press the cancel button on the rescan dialog box ...

**Comment by skironDotNet** [comment]
Ok, just did fresh like start and now I know what you mean, it will still scan but only last 1 or 2 blocks, which is "safe" but being security freak as I am, the first address has been already sent to lighwalletd and it did learn the IP.
Honestly I don't know how scanning works exactly, I know that in SPV wallets like Coinomi, TrustWallet, the public addresses are sent to the server to check if they have balance, and the response return tx info.

From being absolute privacy freak, I would never enter my real seed, and start scanning with public server. I stick with dummy account, change server, then real account :)

**Comment by hhanh00** [comment]
That's understandable. Then yeah - use a dummy account for the time being.
