### ISSUE TITLE
Allow user to enter amount both into ZEC and USD fields

### ISSUE THREAD

**Issue by bobanm** [hhanh00/zwallet#11]
In send view, both ZEC and USD values are already shown and typing something in the first field already updates the second field.

Instead of introducing a checkbox in advanced options which switches positions of ZEC and USD fields, allow user to input value in any of the 2 fields.

**Comment by hhanh00** [comment]
I think it should be clear which field is the input and which one is the calculated one. Then if you take a screenshot, you know what you wanted.

**Comment by bobanm** [comment]
My point is: It's much better UX if both fields are input fields and they are in sync, so any change in one immediately updates the other.

That's quite a standard feature of mobile wallets and I think the users are very accustomed to it.

**Comment by hhanh00** [comment]
I understand but I don't like this design, sorry.

**Comment by hhanh00** [comment]
I'll keep this issue open. In case more people prefer it this way, we could implement it.

**Comment by hhanh00** [comment]
I've implemented in https://github.com/hhanh00/zwallet/commit/6bc1eb519ccb5ccacf2e0e5cc08b6af9363ac3ee
Thanks for the suggestion.
