### ISSUE TITLE
Feature Request: Allow 'Include My Address In Memo' receiver selection option

### ISSUE THREAD

**Issue by autotunafish** [hhanh00/zwallet#113]
### Subject of the issue
The 'Include My Address In Memo' option only applies a Sapling receiver. 

### Your environment
 1.4.3, tested on mac but seemingly all flavors

### Steps to reproduce
Create a tx and select the 'Include My Address In Memo' option. 

### Expected behaviour
Allow another option for the desired return receiver type (or types i.e. full or partial UAs, though they do get large..)

### Actual behaviour
No receiver selection option exists, only a Sapling receiver is allowed in the use of the 'Include My Address In Memo' option.

**Comment by hhanh00** [comment]
![image](https://github.com/hhanh00/zwallet/assets/222239/eb9922df-a903-4aa2-8e6d-8a4c7a1e664a)
