### ISSUE TITLE
The AppImage version of Linux desktop wallet crashing when sending T2T 

### ISSUE THREAD

**Issue by skironDotNet** [hhanh00/zwallet#114]
### Subject of the issue
the app is crashing after hit final send button 

### Your environment
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa
GU:  XFCE

### Steps to reproduce
Exclude all shield notes, go to QR T address, click Send arrow button, enter T address, follow with steps to send 

I don't know if this relates to XFCE, or to Mint, or to AppImage or missing packages, I don't know if YWallet provides any logs
I will keep posted, maybe I'll try in Mint Cinnamon and Ubuntu

**Comment by skironDotNet** [comment]
Same on Mint Cinnamon and Ubuntu.
On Ubuntu executed the wallet from Terminal, and here are the log 

> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidSecretKey', native/zcash-sync/src/note_selection/builder.rs:305:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

**Comment by skironDotNet** [comment]
Confirmed works on Android

**Comment by skironDotNet** [comment]
Also crash when trying to send all shield notes to shield address, 

> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidSecretKey', native/zcash-sync/src/note_selection/builder.rs:305:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)

**Comment by hhanh00** [comment]
See #111 #104

**Comment by skironDotNet** [comment]
for sure not #111 because I've read all the issue and were paying attention but #104 I need to test

**Comment by hhanh00** [comment]
Have you changed the derivation path of the taddr?

**Comment by skironDotNet** [comment]
Yes, but the other test was from imported sapling private key only and also crash. I did disable the sound option as mentioned in #104 and didn't help.
The error is solid meaning it does not imply the sound, 

> thread '' panicked at 'called Result::unwrap() on an Err value: InvalidSecretKey', native/zcash-sync/src/note_selection/builder.rs:305:46

On Windows all works whether changed derivation and doing T2T or imported sapling priv key only account and sending from that sapling. Linux is doomed for send, Android 12 is doomed for connect (but I don't care about Android).

Thank you for your time

**Comment by hhanh00** [comment]
If you import a sapling key, you cannot make t2t txs. There is no seed phrase and, therefore no transparent key. However, the app should not crash and that's a bug.

**Comment by hhanh00** [comment]
<img width="499" alt="image" src="https://github.com/hhanh00/zwallet/assets/222239/64fcd143-9af7-40bf-8cea-65f0ce9a277a">

Spendable balance is 0 and it didn't crash.

**Comment by skironDotNet** [comment]
Sorry the thread title started as T2T because that's what I was originally testing, then wanted to send from sapling as normally you would use the wallet and crashed. The screen you are showing is OK I all understand that now, but past that screen on final confirmation when click send, the wallet just stops, with error mentioned (if started from terminal as `./Ywallet-latest-x86_64.AppImage`)

Let me know if there is anything I can do to help investigate that, I can test different distributions, etc. Unfortunately I don't code in any programming language you do so I can't help code/debug.
Thanks!

**Comment by skironDotNet** [comment]
It works now so I don't know what was the problem, maybe the sound thing. Definitely works on new wallet, I think I had some scrambled transaction in the wallet that was crashing the app
