### ISSUE TITLE
On Android using custom server will show as Disconnected

### ISSUE THREAD

**Issue by skironDotNet** [hhanh00/zwallet#115]
Same server works fine on Linux Desktop wallet, but on Android shows Disconnected. I tried to install WI-FI certificate of my server and didn't help, why would it not work? Expired CA certificates on mobile? Any other reason and/or a bug

Related to https://github.com/hhanh00/zwallet/issues/114
Chicken egg situation, server works on desktop but crash, mobile can send T2T but can't use custom server :(

**Comment by hhanh00** [comment]
Check that your server is reachable (nat/firewall)

**Comment by skironDotNet** [comment]
you are talking to someone who has over 20 years of programming experience, managing own docker container, networks, servers etc, seriously?

If I'm on same exact WI-FI and on Linux I can connect, but on the phone I can't then this is not about my server.

> Same server works fine on Linux Desktop wallet, but on Android shows Disconnected.

The default lighwalletd option connects ok, so only thing I can think of is the SSL cert validation and I'm using LetsEncrypt. I don't know how Android is managing CA certificates updates to make sure it has latest full chain for validation.

Would be nice if the app had a screen to access logs

**Comment by hhanh00** [comment]
Seriously, you think I didn't test it? I think your attitude is improper. Next time, you will be banned.

**Comment by skironDotNet** [comment]
My attitude? I'm reporting issues not to make you feel bad but to let you improve if you would like.
If you want I can give you my server URL, and you can test with custom. With android it's hard to tell it could be anything from device hardware all the way to Android OS and your app may have nothing to do with it, but I reported this as I see from user perspective. I guess displaying some status to the user of why "Disconnected" could be valuable, but I'm starting to feel you developed it for yourself only, and you have complete right to take that stand. But since your wallet is on official ECC website, the whole world is counting on you

**Comment by hhanh00** [comment]
![Screenshot_2023-10-14-12-52-51-59_27468b36eb8f25f08303b76a83fed9af.jpg](https://github.com/hhanh00/zwallet/assets/222239/ddcce0ea-03c2-4f80-9a00-76bb5711c30a)

**Comment by skironDotNet** [comment]
on the picture it is without SSL, that's not really a test in regards to production use case.

You would need full setup like described in here https://github.com/zcash/lightwalletd#production-usage

You can host from VM or from Docker, but you need to use host header to fake the domain and have a cert that is not self signed, so I don't know how you would obtain it. Let's Encrypt can give you real chain cert but you need some VPS with a domain to be publicly accessible. I don't know if you have such setup or not, so sorry just trying to help.
I can generate a cert for you with mine test domain, and the whole docker ready to run on local machine if you would like.
Let me know if there anything I can do to help. Thank you

**Comment by hhanh00** [comment]
Can your server be used by Zingo?

**Comment by skironDotNet** [comment]
yes, works perfectly fine. I use zcash original lighwalletd source https://github.com/zcash/lightwalletd 
with full TLS on same port just my own domain

**Comment by hhanh00** [comment]
ok - what's your url?

**Comment by skironDotNet** [comment]
I would like to keep it private from others, please post your z addr, I'll send it as memo

**Comment by hhanh00** [comment]
![Screenshot_2023-10-18-23-25-00-69_27468b36eb8f25f08303b76a83fed9af.jpg](https://github.com/hhanh00/zwallet/assets/222239/cd78a065-449c-457b-8b5d-f862375a695c)

Custom url from regional lwd works.

**Comment by skironDotNet** [comment]
Ok, I'll re-check my SSL cert, and maybe debug on my phone if that's written using Android studio.

Thank you for your time
