### ISSUE TITLE
Not able to run appimage after v1.4.3

### ISSUE THREAD

**Issue by sandakersmann** [hhanh00/zwallet#121]
I'm able to run appimage v1.4.3, but not the two versions after that. I'm on Ubuntu 22.04.3 LTS.

**Comment by hhanh00** [comment]
This is caused by a version conflict between the version of libstd++ bundled in the app image and the host. There doesn't seem to be a clear solution besides removing the dependency on audioplayers.

**Comment by hhanh00** [comment]
The pre release 1.5.0 should work on.

**Comment by sandakersmann** [comment]
It indeed works :)
