### ISSUE TITLE
Crash during rescan

### ISSUE THREAD

**Issue by rex4539** [hhanh00/zwallet#122]
### Subject of the issue
App crashes always during rescan.

### Your environment
* 1.5.0
* macOS Sonoma

### Steps to reproduce
Start rescanning from 735000.

### Expected behaviour
Rescan finishes.

### Actual behaviour
App crashes around 1500000 blocks.

[ywallet-2023-12-18-204631.ips.zip](https://github.com/hhanh00/zwallet/files/13707483/ywallet-2023-12-18-204631.ips.zip)

**Comment by hhanh00** [comment]
Thanks for the report, does the scan eventually finish if you restart the app or does it keep on crashing?

**Comment by rex4539** [comment]
Keeps on crashing. Endless loop.

I don't recall any changes to defaults.

**Comment by hhanh00** [comment]
How about "retrieve transaction details"?

**Comment by hhanh00** [comment]
There is an update that may fix it.

**Comment by rex4539** [comment]
Looks like it's been fixed. The progress has started again.
