### ISSUE TITLE
UI issues during rescan

### ISSUE THREAD

**Issue by rex4539** [hhanh00/zwallet#123]
### Subject of the issue
When trying to rescan, there are multiple UI issues.

### Your environment
* 1.5.0
* macOS Sonoma

### Steps to reproduce
Start a rescan.

### Expected behaviour
1. After pressing the checkmark to start the rescan, user is redirected to the Balance screen where the progress bar is shown.
2. When the rescan process is in progress, the progress bar doesn't say PAUSED.
3. If the rescan process is indeed paused then the message says "PAUSED - Click to Resume", not "Tap" since I'm on a desktop computer.

### Actual behaviour
1. After pressing the checkmark to start the rescan, nothing happens on the screen. 
2. On the balance screen, the progress bar says it's been paused but the rescan is actually in progress and the progress bar is moving. Clicking on the bar, nothing happens.
<img width="1227" alt="Screenshot 2023-12-19 at 08 37 28" src="https://github.com/hhanh00/zwallet/assets/227442/548cfd15-de4a-42d6-b809-da6a7cbb4931">
3.  The message says "PAUSED - Tap to Resume" but I'm on a desktop computer so "Tap" is not appropriate here. "Click" should be written instead.

**Comment by hhanh00** [comment]
It is caused by an issue with the mainnet server. It keeps disconnecting
clients.

**Comment by hhanh00** [comment]
Tap or Click, I think this is clear enough.
