### ISSUE TITLE
Feature request: please disable smart box for amount 

### ISSUE THREAD

**Issue by skironDotNet** [hhanh00/zwallet#134]
In current smart box there is not way to put custom decimal point
I'm still at version version: 1.4.3+473 maybe fixed in later but in case it's not see the clip

https://github.com/hhanh00/zwallet/assets/2981715/0cee0207-8aba-4249-beac-17cbf274ca1a

**Comment by hhanh00** [comment]
What is smart box?

**Comment by hhanh00** [comment]
Yeah, that is changed in 1.5
