### ISSUE TITLE
Error message in terminal when running Ywallet-latest-x86_64.AppImage

### ISSUE THREAD

**Issue by metalworker2** [hhanh00/zwallet#141]
### Subject of the issue

Error message when running `./Ywallet-latest-x86_64.AppImage` on up to date Debian machine:

```
/tmp/user/1000/.mount_YwalleKhCccs/ywallet: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /tmp/user/1000/.mount_YwalleKhCccs/lib/libaudioplayers_linux_plugin.so)
```

could not figure out how to find and install whatever it thinks is missing.

### Your environment
Debian 12

### Steps to reproduce

- Start Debian 12 OS with up to date software
- Download `Ywallet-latest-x86_64.AppImage` from https://ywallet.app/installation/
- Open download directory and run `./Ywallet-latest-x86_64.AppImage` 
- See error message 

### Expected behaviour

I expect Ywallet app to run without error message.

### Actual behaviour

Get error message in terminal, Ywallet does not start.

**Comment by hhanh00** [comment]
Should work now. The website was pointing to an old version. (You need to download the latest one)

**Comment by metalworker2** [comment]
Yes it works now. Thanks
