### ISSUE TITLE
Balance field not showing

### ISSUE THREAD

**Issue by Ecoinomical** [hhanh00/zwallet#143]
### Subject of the issue
When starting Ywallet all fields are showing except the balance/QR code field.

### Your environment
* Laptop I7 16 GB
* Ywallet 1.5.4
* Linux Ubuntu based OS : 22:04 and 23.10. tried Ubuntu/Lbuntu/Linux Mint etc.
* Previous: None

### Steps to reproduce
- Install Ywallet (flatpak)
- Start wallet and create new or recover account
- Add account

### Expected behaviour
A new account with balance/QR code should show up showing 0.000

### Actual behaviour
Blank (pink) field is visible were balance/QR code should be after startup.
Toggling back and forth through menus or restarting wallet does not change this behaviour.
Happens with recover and create new account.
Happens with Yec and Zec.

**Comment by hhanh00** [comment]
Could you check the setting hide balance in the privacy section?

![image](https://github.com/hhanh00/zwallet/assets/222239/2e46ffff-16dc-49a7-9726-8abddb09494b)

**Comment by Ecoinomical** [comment]
Tested with Linux Mint Cinamon 21, I  did a fresh install of Ywallet ==> all other settings match your screenshot ==> result: no balance showing.
I tried other [hide balance] options: view off and view on but all give the same result.

**Comment by hhanh00** [comment]
I just tried with LM. The window may start too short. Did you try resizing/scrolling? The dots are the address indicator.

![image](https://github.com/hhanh00/zwallet/assets/222239/64d53d09-14e0-4ecd-b027-723bfbf57bce)

**Comment by Ecoinomical** [comment]
I tried again, first scrolling top to bottom ....no change
Then I tried resizing screen resolution  also no change (tried 1920 to 1080 range).
I would like to add that Debian based system have no issue with the balance so Linux Mint LMDE will work , Ubuntu based (Cinamon etc ) not.....
![Screenshot from 2024-03-28 18-30-57](https://github.com/hhanh00/zwallet/assets/113306668/37d73d8c-1274-40e1-8bb4-4695cfef2371)
![Screenshot from 2024-03-28 18-31-21](https://github.com/hhanh00/zwallet/assets/113306668/4457f658-dcb5-4956-890d-2246508e053f)
![Screenshot from 2024-03-28 18-33-22](https://github.com/hhanh00/zwallet/assets/113306668/7b302215-dde5-418f-93e2-b38d5c7588bc)

**Comment by hhanh00** [comment]
![VirtualBox_mint_29_03_2024_03_56_34](https://github.com/hhanh00/zwallet/assets/222239/66e16dd8-5392-44e4-a688-de42734f11b5)

For your screenshot, it looks related to a problem with fetching real time quotes.

**Comment by Ecoinomical** [comment]
Wallet is connected to internet and synced.

The Debian based Linux distros show balance even with no internet connection.

**Comment by Ecoinomical** [comment]
Accidently closed this issued while issue is still open/unsolved.

**Comment by hhanh00** [comment]
I'm not sure what you expect me to do. I have installed it on a fresh mint
instance and as you can see, it is working fine.
