### ISSUE TITLE
Receiving address may contain a mix of receivers from multiple accounts

### ISSUE THREAD

**Issue by AArnott** [hhanh00/zwallet#158]
### Subject of the issue

YWallet shows a unified receiving address containing sapling and orchard receivers from one account and a transparent receiver from a *different* account.

### Your environment

1.6.1+538/f2970c23
Android

### Steps to reproduce

I expect this will repro the problem based on the steps I took. But I didn't try them on a fresh install myself.

1. Create a new account with a new seed phrase. This will use account index 0. 
2. Create a new account, using the import feature and the same seed phrase used by the first account. Set the account index to 3.

With the new account selected, copy the default address shown by the home screen, which is a unified address including all receivers.

### Expected behaviour

All receivers direct money into the new account (with account index 3).

### Actual behaviour

The orchard and sapling receivers are derived from account index 3.
The transparent receiver is derived from the original account (account index 0) using *address index* 3.

As a result, ZEC sent to the unified address will arrive in account index 3 if sent to the shielded receivers, or account index 0 if sent to the transparent receiver.

**Comment by hhanh00** [comment]
We inherited this weird behavior from zec wallet lite. The extra transparent addresses increment address index, whereas extra shielded addresses increment account index.

**Comment by AArnott** [comment]
Does it only impact the displayed receiving address, or does sync download transactions from the wrong transparent addresses as well?

**Comment by hhanh00** [comment]
It downloads from the address displayed. You call it wrong because it is
not what you expect or because of some zip?

**Comment by AArnott** [comment]
Both my expectation and the ZIPs.

[ZIP-32](https://zips.z.cash/zip-0032) states that it builds on top of BIP-44 which specifies [the derivation path for transparent addresses](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#user-content-Path_levels) to be `m / purpose' / coin_type' / account' / change / address_index`. ZIP-32 re-states account index as in the same derivation position that BIP-44 specifies. 
ZIP-32's Motivation section also calls out how the intent is to have logical "accounts" from which all keys are derived.

It is also the way Bitcoin wallets operate: one can create multiple accounts with a single master seed, and then within that account can create many addresses. 

YWallet however is splintering the concept of account by creating and joining addresses from across accounts. It deviates from every other wallet I've seen that supports more than one account (ZECWallet excepted, apparently).

**Comment by hhanh00** [comment]
Backward compatibility was deemed more important especially since at that
time UA didn't even exist. Now we cannot change the derivation path without
forcing users to move their funds.

It is just gonna be a known quirk.

**Comment by AArnott** [comment]
Yes, I can appreciate the difficult position you're in. 
You mentioned it as "a known quirk", but who knows it? It seems safe enough to be unknown if a user never uses a seed phrase across wallets, but we know users do actually do that. Can this quirk be documented prominently enough (perhaps on the Import Seed screen) so users are aware?

**Comment by hhanh00** [comment]
My mistake was to call the field "account index", "address index" could
have been preferable but I thought some may think it is the address
diversifier index.

**Comment by AArnott** [comment]
Well, you _are_ using the value for account index for the shielded pools, so "address index" would have been misleading there too.

**Comment by hhanh00** [comment]
There is no address index in ZIP-32, so the account index could be
considered an address index. Anyway, it is a legacy now.

**Comment by AArnott** [comment]
"address index" may not be mentioned in ZIP-32, but ZIP-32 explicitly builds on BIP-44, where address indexes _are_ a thing, so address index is still a term that applies in Zcash, if only to transparent addresses.
