### ISSUE TITLE
Camera not working on AppImage

### ISSUE THREAD

**Issue by sourcesolver** [hhanh00/zwallet#167]
I'm using ywallet as an appimage, is there a reason the camera to scan a QR code didn't work on it? I also added myself to the video group on /dev/video and then rebooted my machine and the camera for the QR still had an exclamation mark. Is there a plugin needed to get the QR code scanner to work through the webcam?

**Comment by hhanh00** [comment]
the camera doesn't work on desktop because it is not supported by Flutter atm.

**Comment by sourcesolver** [comment]
Thanks for the honest answer. I will try and find a KDE compliant QR camera app.
