### ISSUE TITLE
Reorg-handling logic may be incomplete

### ISSUE THREAD

**Issue by defuse** [hhanh00/zwallet#18]
When a reorg occurs, zcash-sync will detect it by noticing that the prev_hash of a future block does not match the hash of its previous block. The code for detecting that is here:

https://github.com/hhanh00/zcash-sync/blob/d2c3e8e6c69ff033e50ed20af75a49a8f3c3c3da/src/chain.rs#L67-L69

That error is caught in the zwallet app, which reacts by making a call to rewind the database height:

https://github.com/hhanh00/zwallet/blob/4887184bde7976eb85730e3de8714095269fe2ed/lib/account.dart#L408-L413

The rewinding logic in zcash-sync is simply a series of `DELETE FROM` statements that remove blocks, sapling_witnesses, received_notes, and transactions with heights greater than or equal to the rewind height:

https://github.com/hhanh00/zcash-sync/blob/d2c3e8e6c69ff033e50ed20af75a49a8f3c3c3da/src/db.rs#L146-L164 

This is potentially problematic, as pre-reorg data may still be present in other parts of the app outside of the database, or the rewinding may be incomplete.

One example of incomplete rewinding is in the marking of notes as spent or unspent. In the scanning logic, a revealed nullifier may cause one of the notes to be marked as spent in the database:

https://github.com/hhanh00/zcash-sync/blob/d2c3e8e6c69ff033e50ed20af75a49a8f3c3c3da/src/scan.rs#L167

However, if that revealed nullifier were to be reorged away, the note should be marked as unspent as it is now spendable by the wallet. The logic to do this is missing. As a result, a user may lose funds by deleting a wallet that has unspent notes erroneously marked as spent.

I recommend implementing aggressive automated testing of the reorg handling logic, perhaps taking advantage of darksidewalletd. The reorg-handling logic is the most likely place to find double-spend bugs and therefore deserves much more review and testing.

**Comment by hhanh00** [comment]
Thanks for the review

> This is potentially problematic, as pre-reorg data may still be present in other parts of the app outside of the database, or the rewinding may be incomplete.

> One example of incomplete rewinding is in the marking of notes as spent or unspent. In the scanning logic, a revealed nullifier may cause one of the notes to be marked as spent in the database:

Reactivating unspent note is indeed missing. The database needs to clear the spent height. Ironically, the reason why unspent is stored as a height (and not as a flag) was specifically in order to be able to rewind with an update statement. But that update statement is not there.

The app does not store data outside the database besides for caching and the cache is cleared when the block height changes.
