### ISSUE TITLE
Allow creating new accounts hierarchically based on ZIP 32

### ISSUE THREAD

**Issue by luckytokidoki** [hhanh00/zwallet#19]
[ZIP 32](https://zips.z.cash/zip-0032) is the standard mechanism by which wallets for Zcash generate shielded addresses and keys deterministically. Adopting this standard can allow users to do a one-time backup of the seed/recovery/backup phrase to recover funds from all future addresses.

Currently Zwallet generates new seed when creating a new accounts. By generating new accounts/address from the same seed, Zwallet users won't need to backup multiple seeds from multiple accounts.

**Comment by hhanh00** [comment]
ZWallet uses ZIP 32 with account index = 0.

I'm not sure I understand what you suggest.

**Comment by luckytokidoki** [comment]
> ZWallet uses ZIP 32 with account index = 0.

Yes, and currently Zwallet will generate a new seed when users want to create a new account. I think users should be able to create a new n accounts with index = n. This way:

> Zwallet users won't need to backup multiple seeds from multiple accounts

As all of their accounts is derived from the same seed. This is a standard behavior in BIP 32 wallets that is used by most cryptocurrency users.

**Comment by hhanh00** [comment]
For shielded wallets, the user needs to remember the index because it is quite expensive to scan addresses. Regular coins can guess the index up to a certain "gap limit" but that is prohibitive for zcash. At the end of the day, the choice is between:
- one different seed per account and index = 0,
- same seed but the user can configure the index

It's quite easy to add the second option but I'm a little worried that some users forget to save the index.

Would diversified addresses work in your scenario?

**Comment by luckytokidoki** [comment]
The wallet doesn't need to automatically generate new address and scan those new address. Instead, when users want to "Add Account", generate the new address directly from the same seed with the next index as the default option. [ZIP-316](https://zips.z.cash/zip-0316) on UA and the current [protocol spec](https://zips.z.cash/protocol/protocol.pdf#page=12) describes derivation based on ZIP-32 to generate diversified payment address.

Current behavior of allowing importing/generating new seed to add a new account can still be included as an advanced option. However, the "primary" seed should be used to generate new accounts with a different index.

**Comment by hhanh00** [comment]
My concern is simply that users will need to backup their account index as well as their seed. This is not usual as regular coins don't require that. 

I was asking whether diversified addresses would cover your use case and not about how to derive them. In other words, in which case would you need N shielded accounts (where N is large)?

**Comment by luckytokidoki** [comment]
Allowing users to configure the index would make the wallet prone to user-mistakes as they might not backup the index along the seed.

I understand that unlike Bitcoin wallets, Zcash users don't need to create a new address for new transaction. However, sometimes you want to have different account for different purpose and generating the different accounts from the same seed is a much better experience for normal folks than having to remember a bunch of different seed phrases.
> For shielded wallets, the user needs to remember the index because it is quite expensive to scan addresses.

Popular wallets such as metamask allow diversified account without requiring users to remember the index. As, adding new account automatically generates new address based on the primary seed with the next index.

**Comment by hhanh00** [comment]
With Ethereum (or any non shielded coin), wallets can restore a seed like this:
- let index = 0
- A = compute address at index
- query server for tx for address A
- increment index
- repeat until there are [gap limit](https://blog.blockonomics.co/bitcoin-what-is-this-gap-limit-4f098e52d7e1) consecutive addresses with 0 transaction

Then show the resulting addresses and let the user pick which one to restore.

For shielded coins, it is not possible to query the tx count for a given address. We need to scan and trial decrypt. Therefore we cannot do what Metamask does and we have to ask the account index.

**Comment by luckytokidoki** [comment]
> * let index = 0
> * A = compute address at index
> * query server for tx for address A
> * increment index
> * repeat until there are [gap limit](https://blog.blockonomics.co/bitcoin-what-is-this-gap-limit-4f098e52d7e1) consecutive addresses with 0 transaction

The mechanism you describe above is true for most UTXO-based public chains but not for all account-based chain like Ethereum. In Metamask for example, when a user install it, they will be given the option of creating an account with a new seed or importing an existing seed. The first account will then be the account at index 0 (new version of Metamask also checks the next index but this was not the default in earlier version). When users want to create a new account in the same Metamask app, it will then generate a new account from the same seed but with different index. This way, users doesn't need to remember the index number. They just need to remember how many accounts were created from the seed, and then manually check new addresses when they try to recover some old seed.

**Comment by hhanh00** [comment]
> This way, users doesn't need to remember the index number. They just need to remember how many accounts were created from the seed, and then manually check new addresses when they try to recover some old seed.

The index number is the same thing as the number of accounts that were created from the same seed. You are basically describing the same process done manually.

**Comment by luckytokidoki** [comment]
I recommend that you try out Metamask if you haven't. Then you will get what I'm trying to say.

Users do not expect Metamask to check all of the address. They just need to manually add address in a new index if they have used it before.

Doing this manually also means that the server will only need to query account/address that the users create.
-------- Original Message --------

**Comment by hhanh00** [comment]
I used metamask... What I am trying to say is that it relies on the ability
to quickly show used accounts. Take that away and the user has to remember
his account index.

**Comment by luckytokidoki** [comment]
> it relies on the ability to quickly show used accounts.

What I'm trying to say is that this is not necessarily true. [In Metamask, "When you restore a wallet from the Secret Recovery Phrase, only the default account (Account 1) will be restored automatically first"](https://metamask.zendesk.com/hc/en-us/articles/360015489271-How-to-add-missing-accounts-after-restoring-with-Secret-Recovery-Phrase). For each old account that users had during original installation, they will have to add it back by "creating" an account.

Now you can say that the users will have to remember if they had created multiple accounts with the seed, but the wallet does not have to check to:

> increment index
> repeat until there are [gap limit](https://blog.blockonomics.co/bitcoin-what-is-this-gap-limit-4f098e52d7e1) consecutive addresses with 0 transaction

Let the users check it out for themselves, the wallet doesn't have to check a bunch of accounts when it first started. Just the "Account 1" at index 0.

**Comment by hhanh00** [comment]
It takes a lot of resources to scan an account and it's wasted if it is not the right one. The user has to remember it. Imagine it's the 10th account. Do you want to scan the blockchain 10 times?

**Comment by luckytokidoki** [comment]
It takes the same resource to scan 10 accounts from 10 different seeds, and to scan 10 accounts for the same seed. The different is, in the former users need to backup 10 different seeds while in the later they only need to store one seed.

> Do you want to scan the blockchain 10 times?

No, but today someone is free to do that on Zwallet by simply creating 10 accounts with 10 different seeds.

**Comment by hhanh00** [comment]
> The different is, in the former users need to backup 10 different seeds while in the later they only need to store one seed.

In the first case, I can restore any of the 10 accounts directly without having to go through the other ones.

Because if the app doesn't let me enter the account index, I would need to restore the seed, then recreate all the intermediate accounts.

**Comment by luckytokidoki** [comment]
> Because if the app doesn't let me enter the account index, I would need to restore the seed, then recreate all the intermediate accounts.

You could argue that average users don't normally create multiple Metamask accounts where there are many empty intermediate accounts.

Also, this could be solved by adding the option that you mentioned before.

> * same seed but the user can configure the index

 Although I would argue it's not the best UX for average users.
 
 Ultimately it's up to you though as the developer. Cheers.

**Comment by luckytokidoki** [comment]
> In the first case, I can restore any of the 10 accounts directly without having to go through the other ones.

Also, what the difference between requiring users to remember **which seed vs which index** they save their money in?

If I have 10 seeds, I will need to remember which seed that I need to restore. If I have one seed with several index, then I don't need to remember which seed, just which index.

Also, many users spend money to save their seed in robust tool/system such as [capsule](https://shop.trezor.io/product/cryptosteel-capsule) or [card](https://shop.trezor.io/product/cryptotag-zeus). As such, it's safer to assume that users would prefer to backup one seed and they create multiple accounts from that seed.

All above are assumptions which will need to be confirmed by user research.

**Comment by hhanh00** [comment]
Exactly, the problem is the UI and the expectations from the users. If they assume the seed is sufficient because it is the case for every coin except zcash (+ monero and other private coins), then they will lose their funds.

**Comment by luckytokidoki** [comment]
> If they assume the seed is sufficient

This is the exact [intention of ZIP-32](https://zips.z.cash/zip-0032#motivation). "A one-time backup of the seed can be used to recover funds from all future addresses."

As such, with ZIP-32, users should expect that backup of the seed is sufficient to recover all accounts derived in the same wallet. Of course, with the exception of imported accounts like in Metamask.

**Comment by hhanh00** [comment]
Yeah but that's misleading. In practice, you need the derivation path too.

**Comment by hhanh00** [comment]
Implemented in a somewhat hidden menu
