### ISSUE TITLE
C Library Incompatibility in Ubuntu 20.04.4

### ISSUE THREAD

**Issue by luckytokidoki** [hhanh00/zwallet#20]
The Linux executable, supplied on the download page, requires GLIBC v 2.34 but by default in Ubuntu the highest version of GLIBC is usually fixed based on Ubuntu version.

```
~$ ./zywallet
./zywallet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./zywallet)

~$ sudo apt-cache policy libc6
libc6:
  Installed: 2.31-0ubuntu9.7
  Candidate: 2.31-0ubuntu9.7
```

**Comment by hhanh00** [comment]
https://github.com/hhanh00/zwallet/releases/tag/v1.2.1

This is a flatpak and can be used on most Linux distributions.

**Comment by hhanh00** [comment]
FYI: The pre-release flatpak was just updated to fix a bug related to the database directory.
