### ISSUE TITLE
btcpayserver integration

### ISSUE THREAD

**Issue by cariaso** [hhanh00/zwallet#21]
This comment is more suited to 
https://github.com/hhanh00/btcpayserver
but that repo doesn't permit issues. 

Based on
https://www.youtube.com/watch?v=9MyHFcGhZJo&t=6m30s
there is a yml fragment which is relevant to starting the zcash / ycash wallet with btcpayserver, but the relevant code does not appear to be part of what was merged into btcpayserver.

Presumably it's relevant to this comment

https://github.com/btcpayserver/btcpayserver/pull/3400#issuecomment-1027679060
 
and should include some new code in
https://github.com/btcpayserver/btcpayserver-docker

to mirrors the monero.yml
https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/monero.yml

Is it possible to get that code integrated into btcpayserver-docker?

**Comment by hhanh00** [comment]
That file is here: https://github.com/hhanh00/zcash-btcpay/blob/main/docker-compose.yml
