### ISSUE TITLE
Sub accounts on Desktop - long press?

### ISSUE THREAD

**Issue by skyl** [hhanh00/zwallet#27]
> To create a sub-account for the current selected account, long press the ‘+’ button, and select “New Sub-account”.

I don't think there is a way to do this on Desktop? Maybe I'm wrong ...

**Comment by hhanh00** [comment]
All the documentation screenshots were captured using the Desktop build.

**Comment by skyl** [comment]
Hrm, I can't seem to figure out how to do it on a track pad on MBP.

**Comment by hhanh00** [comment]
Works fine for me on MBP too.

**Comment by skyl** [comment]
works beautifully, my mistake! thanks!
