### ISSUE TITLE
ywallet often requires force kill on mac

### ISSUE THREAD

**Issue by skyl** [hhanh00/zwallet#28]
I think this only happens when it is trying to sync; but, it would be a nice to have if it would shutdown cleanly regardless of what it is trying to do with sync? I'll check to see if it happens even when sync is complete ... if I can ever sync again ... seems like the lightwalletd backends are not behaving too well right now ;/

**Comment by hhanh00** [comment]
It may take a while to close but it should eventually disappear without force closing.

**Comment by hhanh00** [comment]
https://github.com/hhanh00/zwallet/commit/02ff9a9efb61681de0f83892a5d1d48138825e2f
