### ISSUE TITLE
Issue with glibc

### ISSUE THREAD

**Issue by pablogzlezmora** [hhanh00/zwallet#30]
I have installed the flatpak version.
When I try to run _ywallet_ with the command:
`flatpak run me.hanh.zwallet.Ywallet`,
I get:
```ywallet: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ywallet)```
The version of my _glibc_ is 2.36-1.
Is there any fix, please?
Arch Linux; flatpak 1:1.12.7-1; windows manager: i3-gaps; ywallet 1.2.11+259

**Comment by hhanh00** [comment]
Interesting... You have the exact same config as I do and it works fine for
me.

**Comment by pablogzlezmora** [comment]
@hhanh00, which is your glibc version, please?

**Comment by hhanh00** [comment]
`ldd (GNU libc) 2.35`

**Comment by hhanh00** [comment]
flatpak has 2.33. I removed some unused packages. Please try https://github.com/hhanh00/zwallet/releases/download/v1.2.12/ywallet.flatpak

**Comment by pablogzlezmora** [comment]
I will check. Thanks.

**Comment by pablogzlezmora** [comment]
It works now. Thanks.
