### ISSUE TITLE
Rescan control

### ISSUE THREAD

**Issue by sellout** [hhanh00/zwallet#37]
I needed to rescan today, but I accidentally selected the default start date (Oct 2018) instead of the correct much more recent birthday. “Cancel Rescan” only lets me pause the rescan as far as I can tell, but I would like to _restart_ the rescan from the proper date and skip a few extra years of scanning.

Also, I think having date selection is a good UI, but in this case I had the birthday block handy from another source, so I actually had to convert that back to a date rather that just provide the exact block.

**Comment by hhanh00** [comment]
You can reset the app in this case. Canceling the rescan would leave the app in an undesirable state.
