### ISSUE TITLE
Privacy Issue: Allow toggling between Message/Memo download settings

### ISSUE THREAD

**Issue by kowalabearhugs** [hhanh00/zwallet#38]
It's my understanding that the lightwallet server learns which tx ids belong to a user who opts to download their memos from the blockchain. This potential privacy issue is mitigated by either downloading all memos (requires a lot more bandwidth) or not downloading memos.

Zecwallet Lite presents these options to the user and allows them to toggle between them. This functionality should be implemented into Zwallet/Ywallet

IMO the default should be not download memos and allow the user to opt-in to memo downloading since it potentially degrades privacy by allowing the lightwallet server learn information about a users transactions.

**Comment by hhanh00** [comment]
This option is present in the settings.

https://ywallet.app/settings/misc/

**Comment by kowalabearhugs** [comment]
Thank you for the reply and for correcting me. 

Is this feature checked by default?

**Comment by hhanh00** [comment]
Yes, because most people want to see their messages and transaction info.

**Comment by kowalabearhugs** [comment]
I'm not sure that most people know that utilizing memos will leak their tx id and metadata to the lightwallet server.
