### ISSUE TITLE
Improvement: Use separate 6-digit pincode for locking or Send

### ISSUE THREAD

**Issue by bits4fun** [hhanh00/zwallet#40]
Current YWallet uses the phone access pincode for locking. Best practice is to separate protection to individual 6-digit application-level pincode. 

Good examples are Algorand's Pera Wallet, Kinesis Money and several others. Ledger Live goes the extra mile by specifiying a password to access the app. IMHO a 6-digit pincode would be an excellent choice.

Having separate pincodes to Ywallet, etc. is like another layer of protection, in case phone access-level has been breached.

**Comment by hhanh00** [comment]
I am not convinced that having two locks provides higher security than one. Especially when the second one is application level and not OS. It seems to me that it would be the equivalent of putting two locks on a door: Whoever can pick one, can pick the other.

**Comment by hhanh00** [comment]
#65
