### ISSUE TITLE
Contacts cannot be modified or deleted

### ISSUE THREAD

**Issue by AArnott** [hhanh00/zwallet#44]
On the [latest beta release](https://github.com/hhanh00/zwallet/releases/tag/v1.2.17%2B327), I see I can create new contacts but I cannot delete or modify them.

**Comment by hhanh00** [comment]
Have you tried #5 and #6 from https://ywallet.app/contact/list/ ?

**Comment by AArnott** [comment]
So... maybe a usability improvement opportunity.

**Comment by hhanh00** [comment]
It is a mobile app first. No right click available.
