### ISSUE TITLE
Different signature for Android apk

### ISSUE THREAD

**Issue by gjf** [hhanh00/zwallet#48]
Latest release of [app-fdroid.apk](https://github.com/hhanh00/zwallet/releases/download/v1.2.17%2B366/app-fdroid.apk) (v1.2.17+366) has a signature that is different for all previous releases. It makes impossible to update the previous version.

Is it possible to use the same signature for all releases?

**Comment by hhanh00** [comment]
The key was updated so that I can upload the aab built by github to Google Play. This is a one time thing.
If you want to upgrade without having to reimport/resync your data, I suggest you use the batch import/export
https://ywallet.netlify.app/save/03.batch/index.html
