### ISSUE TITLE
Payment URIs do not work in YWallet (desktop)

### ISSUE THREAD

**Issue by Edicksonjga** [hhanh00/zwallet#49]
Payment URIs (Zip-321 if I'm not mistaken) don't work in YWallet for Desktop, but they do work in YWallet for mobile.

Knowing that within the Zcash ecosystem there are platforms that use payment URIs, I suggest that they also add that feature in YWallet for Desktop.

One of the platforms that most demands this function is [Free2Z](free2z.cash), in which there are many users who create pages from their computers, to activate these pages URIs are used, made up of an address, ZEC amount and an encrypted memo containing a command and an ID.

Example:
```
zcash:zs1lm4habdbdxdp39462927n0lpxz490uq5nxasz6mql555f96hql4h927jfkf2a42j7mp0slck2uvjjk?amount=0.001&memo=eyJhY3QifiJwYWdlX2Z1bmQitCJpZCI6Ijk1NzExj2M3LW234DkwMy04NWNjL789IwNzllNzdlMSJ9
```

This data is difficult to type manually and doing so increases the chance of mistyping the data and the user submitting a failed transaction.

Since YWallet for mobile does support that feature, it would be great if it was also in YWallet for Desktop.

Thank you very much in advance!

**Comment by skyl** [comment]
Last I check they worked although maybe could be made a little more intuitive ...

https://github.com/hhanh00/zwallet/issues/25#issuecomment-1181522650

**Comment by hhanh00** [comment]
It opens a pick file dialog box now. There isn't an easy way to give a payment URI anymore.

**Comment by hhanh00** [comment]
Implemented in build 370 (Windows & MacOS)

**Comment by Edicksonjga** [comment]
> Implemented in build 370 (Windows & MacOS)
> 

Thanks, thanks, thanks! 🎉🎉🎉
![IMG_20230208_205943_370.png](https://user-images.githubusercontent.com/37910384/217688250-c772cf8d-b4c2-45bb-89d0-11a83bdd9a8c.png)
