### ISSUE TITLE
Wallet does not open

### ISSUE THREAD

**Issue by yoditar** [hhanh00/zwallet#50]
I installed the new update (desktop version on Windows 10) , synced the wallet and when I try to open it again it won’t open. Any solution? Thank you!

**Comment by hhanh00** [comment]
Please fill out the issue template. I need more information.

**Comment by yoditar** [comment]
### Wallet does not open
I installed the new update (desktop version on Windows 10) , synced the wallet and when I try to open it again it won’t open.

### Your environment
* version of YWallet: 1.2.17.0
* platform and version. Windows 10.
* if you were upgrading, the previous version you had: 1.2.16

### Steps to reproduce
I try to open the wallet and it won't open. A blank screen appears for 1 second and closes. 

### Expected behaviour
The wallet must be opened in the new, synchronized version. 

### Actual behaviour
The wallet does not open.

**Comment by hhanh00** [comment]
Did you install the zip or the version from the store?
What accounts did you have on 1.2.16? zcash, ycash, both?
What's the build #? The latest is 371.

**Comment by yoditar** [comment]
Did you install the zip or the version from the store?

zip version: https://github.com/hhanh00/zwallet/releases/download/v1.2.17%2B370/ywallet.zip

What accounts did you have on 1.2.16? zcash, ycash, both?

Only Zcash

What's the build #? The latest is 371.

In the website, I only see 370.

**Comment by yoditar** [comment]
The version on Github of ywallet.zip v1.3.0+371 that is downloaded is v1.2.17+370.

Please could you check it and confirm. Thanks!

https://github.com/hhanh00/zwallet/releases

**Comment by hhanh00** [comment]
I have tried reproducing this scenario on a fresh installation of Windows but it works fine. 
You could try starting from a command prompt and see if the app reports any error message.
In any case, you can recover from seed instead of upgrading. First delete or move the directory `C:\Users\<username>\AppData\Local\databases` and launch ywallet

**Comment by yoditar** [comment]
Problem solved! I had to delete the folder you told me (databases) to allow the wallet to run smoothly. Wallet synced to the latest version and enjoying all it has to offer. Thanks a lot Hanh!

**Comment by hhanh00** [comment]
Thanks.
