### ISSUE TITLE
bad-orchard-bundle-authentication

### ISSUE THREAD

**Issue by AloeareV** [hhanh00/zwallet#53]
### Subject of the issue
The bad-orchard-bundle-authentication seems to be effecting Ywallet as well as zingo. It's not my screenshot, so I don't have anything in the way of details about environment, reproduceability, etc., but it's affecting multiple wallets now, so I'm guessing it's something to do with librustzcash or zcashd. https://github.com/zcash/zcash/issues/6440#issuecomment-1433349197

**Comment by hhanh00** [comment]
This is happening on wallets that received funds from zingo. I think that somehow it made an output note that cannot be spent.

**Comment by hhanh00** [comment]
https://github.com/zcash/zcash/issues/6440
