### ISSUE TITLE
Send Funds Decimal Point Glitching

### ISSUE THREAD

**Issue by fluidvanadium** [hhanh00/zwallet#55]
### Subject of the issue
Send funds is glitchy

### Your environment
* 1.3.0+371/2274528f
* Android 11

Decimal place jumps around

https://user-images.githubusercontent.com/111296437/219493276-839e008e-72ba-4d07-807d-2e516ba40e7e.mp4

**Comment by hhanh00** [comment]
Fixed in 1.3.2
