### ISSUE TITLE
Importing View Key causes crash when selecting Main Address Type

### ISSUE THREAD

**Issue by wbaby** [hhanh00/zwallet#56]
ZCASH

Windows Client 1.3.2

If the import is View Key, After a full rescan sync,
Click the small QR code icon to enter the Receive ZEC page,
It will crash when you manually uncheck the three options of T S O in Main Address Type

**Comment by hhanh00** [comment]
Please fill the issue form completely.

What viewing key are you using?

**Comment by hhanh00** [comment]
Closed due to inactivity
