### ISSUE TITLE
account deletion required

### ISSUE THREAD

**Issue by wbaby** [hhanh00/zwallet#57]
If creating too many accounts, be able to delete those that may no longer be needed

**Comment by wbaby** [comment]
Sorry, I found out that this function already exists, and the sliding account can be changed into a delete option. I use the Windows client.

**Comment by aerique** [comment]
Sorry to comment on a closed issue but it is totally not obvious to me how to delete an account on the Linux AppImage desktop client (besides editing the database).

A quick search doesn't show anything for me either.
