### ISSUE TITLE
Snap addresses should be time-based

### ISSUE THREAD

**Issue by AArnott** [hhanh00/zwallet#60]
A YWallet may be restored from a seed phrase on several devices. Getting a snap address should guarantee to provide a never-before-seen address, and that will never be seen again. But if two YWallet installations share a seed phrase, an incrementing counter-based snap address means each wallet will produce the same sequence of snap addresses. Far from providing a fresh address, this risks reuse and possible identity linking between two transactions.

Can the unique counter perhaps be based on seconds since some fixed date or something? That means the only risk of a reused snap address would occur if two YWallets were open and Snap was pressed at the exact same time, which is a far less likely situation.

[As seen on Discord](https://discord.com/channels/1016721702148911186/1016721702606077984/1079169182509305878).

**Comment by AArnott** [comment]
@hhanh00 I'm delighted if this work is done. However I don't see a linked commit, and reviewing the recent commits in main doesn't suggest a match either. Did this get done?

**Comment by hhanh00** [comment]
https://github.com/hhanh00/zwallet/commit/d444ca3cc920fc650a1a0ea1d23b8e076f94c152
