### ISSUE TITLE
YWallet on linux need to be run as root

### ISSUE THREAD

**Issue by james-katz** [hhanh00/zwallet#62]
### YWallet on linux need to run as root
Downloaded the AppImage of YWallet, tried to run, but got  `Access denied (os error 13)` error.
Running as root it starts up ok.
Running as root I noticed that YWallet creates a database directory on root directory `/databases`

### Your environment
* YWallet version: [v1.3.4+382](https://github.com/hhanh00/zwallet/releases/tag/v1.3.4%2B382) / [Ywallet-latest-x86_64.AppImage](https://github.com/hhanh00/zwallet/releases/download/v1.3.4%2B382/Ywallet-latest-x86_64.AppImage)
* OS: Linux Mint 21

### Steps to reproduce
Download and run the AppImage on Linux Mint 21.

### Expected behaviour
The `databases` directory should be created in the home directory: `~/.databases`.

### Actual behaviour
YWallet tries to access a directory in the root directory '/databases`
```
$ ./Ywallet-latest-x86_64.AppImage
[...]
flutter: db path /databases
flutter: Initializing ZEC
flutter: Init error: Permissão negada (os error 13)
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', native/zcash-sync/src/coinconfig.rs:145:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Abortado (imagem do núcleo gravada)
```

**Comment by hhanh00** [comment]
Linux Mint does not set `XDG_DATA_HOME` [specs](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) and therefore it defaults to blank. Either install a windows manager that does or simply set it in your `.bashrc`. For example,
```
export XDG_DATA_HOME=$HOME
```
