### ISSUE TITLE
AppImage does not start

### ISSUE THREAD

**Issue by hotcapy** [hhanh00/zwallet#66]
**Subject of the issue:**
AppImage does not start, there is an error message in terminal output.

**Environment:**
YWallet v1.3.4+389
Not works on Whonix OS VM (Debian)
Works on ArchLinux Host

**Steps to reproduce:**
1. Download YWallet x86_64 AppImage from GitHub releases page.
2. `$ chmod a+x Ywallet-latest-x86_64.AppImage`
3. `$ ./Ywallet-latest-x86_64.AppImage`

**Expected behaviour:**
YWallet launches.

**Actual behaviour:**
`/tmp/.mount_Ywallei2zHo1/ywallet: symbol lookup error: /tmp/.mount_Ywallei2zHo1/usr/lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: wl_proxy_marshal_flags`

If started via GUI double-click instead of terminal command, still nothing happens.

**Question:**

Looks like despite it is AppImage, it has some system dependencies required to launch. I would be really grateful if someone tells me what packages am I missing.

**Comment by hhanh00** [comment]
1.3.5+390 does not work.
The current latest release is https://github.com/hhanh00/zwallet/releases/tag/v1.3.4%2B389

**Comment by hotcapy** [comment]
Thanks for answering!

I'm an Arch person, and my knowledge in Debian is poor, unfortunately. Could you please specify, which exactly package I should install to make it work?

I couldn't find separate "wayland" package in repositories, but there are many different components mentioning it in it's name.

Wiki says that Wayland usually comes with desktop environment/compositor, but Whonix OS uses XFCE which have no Wayland support. I believe installing another desktop environment just to get Wayland dependency isn't an option for Whonix OS.

Thank you in advance for any help.

**Comment by hhanh00** [comment]
Did you try GTK?

**Comment by hotcapy** [comment]
You mean install some GTK related packages, or force AppImage to use GTK someway?

**Comment by hhanh00** [comment]
Install a program that uses gtk (like chromium) or install gtk libs directly
