### ISSUE TITLE
History, Budget, Wallet P&L not correct after pool transfer to Orchard

### ISSUE THREAD

**Issue by rex4539** [hhanh00/zwallet#71]
### Subject of the issue
Account History, Budget, Wallet P&L are not shown correctly after performing pool transfer from Sapling to Orchard.

### Your environment
* version of YWallet **1.3.7+426**
* platform and version. **iOS & macOS**

### Steps to reproduce
Have some ZEC on Sapling. Using the Pool Transfer feature, move them all to Orchard.

### Expected behaviour
History, Budget, Wallet P&L show correct data.

### Actual behaviour
History, Budget, Wallet P&L do not take Orchard into account and show zero ZEC, although the account screen shows the balance correctly.

**Comment by hhanh00** [comment]
It looks ok to me. Can you provide more info?

**Comment by rex4539** [comment]
Sure, what info do you need?

**Comment by hhanh00** [comment]
btw, the charts sample once per day. Screenshots would help.

**Comment by rex4539** [comment]
I masked the amounts but I hope it makes sense now. The pool transfer occurred in January.

<img width="996" alt="Screenshot 2023-03-20 at 11 14 15" src="https://user-images.githubusercontent.com/227442/226300816-2b7f341d-44a6-4447-b5e6-e59aa0dbde0b.png">
<img width="779" alt="Screenshot 2023-03-20 at 11 15 36" src="https://user-images.githubusercontent.com/227442/226300859-d4b6d970-5faf-4f32-b1d5-cebebcdc0825.png">
<img width="996" alt="Screenshot 2023-03-20 at 11 16 03" src="https://user-images.githubusercontent.com/227442/226300882-20752c2a-6dee-4a0c-a1de-279d15905247.png">

**Comment by hhanh00** [comment]
A pool transfer doesn't move funds out of the account. Therefore the
transaction amount is just -fee.
