### ISSUE TITLE
After upgrade of macos version, accounts are missing

### ISSUE THREAD

**Issue by hhanh00** [hhanh00/zwallet#72]
### Subject of the issue
App shows the "New Wallet" page after upgrading from 1.3.5 to 1.3.6.

### Your environment
* version of YWallet: 1.3.6
* platform and version: MacOS
* if you were upgrading, the previous version you had: 1.3.3

### Steps to reproduce
- Create an account on 1.3.3
- Upgrade to 1.3.6

### Expected behaviour
Account should be migrated

### Actual behaviour
New account page

**Comment by hhanh00** [comment]
From version 1.3.6 onward, YWallet is signed and notarized. This removes the "Apple can’t check app for malicious software" pop up and allow smooth installation.
However, it removes the sandbox and changes the home directory.
The old wallet files are in the old location.

```
cp -r $HOME/Library/Containers/me.hanh.ywallet/Data/databases $HOME
```

**Comment by luckytokidoki** [comment]
An issue similar to this is also present with the flatpak build for v1.3.6
Tested on Ubuntu 20.04

**Comment by hhanh00** [comment]
Flatpak and flathub have different sandboxes.

**Comment by luckytokidoki** [comment]
I have been upgrading the app by downloading and installing the flatpak file from ywallet.app
When I upgrade to 1.3.6, my wallet is not detected. As soon as I installed the 1.3.3 version, it worked again.

Did 1.3.6 change the sandbox from flatpak default to flathub default? Or, do you mean that if I install the app through flatpak and flathub, I will have different sandbox? To be clear, I have only been installing the flatpak files downloaded from the website.
