### ISSUE TITLE
Codesign build resets wallet

### ISSUE THREAD

**Issue by rex4539** [hhanh00/zwallet#73]
Not sure if this is known but upgrading to the codesign build on macOS, resets the wallet and you have to restore/rescan.

I did that and then all seemed ok. But then the next day I relaunched the app and it reset the wallet again. So there seems to be a bug there.

Let me know how I could help with this.

Important to note that when going back to previous build, everything is normal and wallet starts where you left off.

**Comment by hhanh00** [comment]
The first part is a known documented issue. https://ywallet.app/installation/

But you shouldn't have this problem the second time.

**Comment by rex4539** [comment]
I actually deleted the databases folder myself earlier because I found it odd that it suddenly appeared there.

macOS applications should write data to a specified folder as in ~/Library/Application Support/Ywallet and not directly to the home folder. This is unexpected behavior.

**Comment by hhanh00** [comment]
Ok, but that is another issue then.
