### ISSUE TITLE
App crashes after clicking “send” button

### ISSUE THREAD

**Issue by AccountForOauth** [hhanh00/zwallet#75]
### Subject of the issue
Hi! While trying to send tokens from t1 address to any other type of addresses app is crashing.
Same behaviour on Windows, Linux, iOS. 
1.3.6 version of app and v1.3.5+398 - both crashes. 
On iOS this one: https://github.com/hhanh00/zwallet/commit/d3d51df6309b72eb9f4b1df764a0e08753975344

### Your environment
* YWallet 1.3.6
* Windows 10, Ubuntu, iOS

### Steps to reproduce
1. choose account to send tokens 
2. Enter address to send
3. Enter amount. 
4. Click “send”
5. Wait for preparing transaction, second screen with transaction details opens
6. Click “Send” (near “Cancell” button)
After this action app crashes and no transaction executed

## Expected behaviour
Transaction executes 

### Actual behaviour
App crashes

**Comment by hhanh00** [comment]
Please mention the actual version of the app. Not "latest version" as it
will change.

**Comment by AccountForOauth** [comment]
> Please mention the actual version of the app. Not "latest version" as it will change.
> […](#)

Ok, fixed

**Comment by AccountForOauth** [comment]
> Seems to work fine... https://user-images.githubusercontent.com/222239/227912707-6bf24f0c-a277-4b25-a62d-ee5a15c0194e.mp4
> 
> On macos, you could try running from the command line.

Is it possible to run from command line on Windows or Linux? If so, where can I find tutorial?

And is it possible to observe elsewhere errors or exceptions thrown by app on my host? May be they will help to find out the reason.

**Comment by hhanh00** [comment]
It is a standard app. Plenty of tutorials on the internet.

**Comment by AccountForOauth** [comment]
> Seems to work fine... https://user-images.githubusercontent.com/222239/227912707-6bf24f0c-a277-4b25-a62d-ee5a15c0194e.mp4
> 
> On macos, you could try running from the command line.

How it works on my iPhone. Crashes after clicking second “send” button. 

https://user-images.githubusercontent.com/120318179/228157364-bd135988-16ea-425e-afc8-7332cfa570a6.MP4

**Comment by hhanh00** [comment]
Anything special about your account?

**Comment by AccountForOauth** [comment]
> Anything special about your account?
> […](#)

Excuse me for the late reply, please. 
I haven’t understand. Special - you mean additional information?

**Comment by hhanh00** [comment]
What you describe is a common scenario. I'm sure a lot of people would have complained already if it was broken. Therefore, there is probably something particular about your account. How did you create it? Any information would be useful. At this point, no one else has your problem.

**Comment by hhanh00** [comment]
Closed for lack of information
