### ISSUE TITLE
iOS 16.5 Beta Crashes. 

### ISSUE THREAD

**Issue by Sil3ntVip3r** [hhanh00/zwallet#77]
### Subject of the issue
I am running iOS Beta's on my iPhone and found I can not open YWallet. When I pick the YWallet App it quickly opens and then closes. 

### Your environment
YWallet Version 1.3.6
iPhone 13 Pro Max iOS 16.5 (20F5039e) Beta

### Steps to reproduce
App will not open when trying to open. 

### Expected behaviour
App should open and allow me to use the wallet.

### Actual behaviour
App crashes on open. 

Interesting enough, I removed the app from my phone, downloaded from the App Store again and now it works lol. 
God's Speed Dev's ! 

![IMG_4320](https://user-images.githubusercontent.com/88293823/231561710-b2fb9408-af9d-43b1-aa2e-3cb5ddc105cc.jpeg)
![IMG_4321](https://user-images.githubusercontent.com/88293823/231561715-d683348b-411e-4136-b2f5-3a099a565ce2.PNG)

https://user-images.githubusercontent.com/88293823/231564075-68bbff02-0a31-47a4-a5a4-980d3215be45.mp4

**Comment by rex4539** [comment]
Not related to the iOS beta. Works fine for me. Something else causes the crash.

Attach to Xcode and post the crash log, along with the console log.

**Comment by hhanh00** [comment]
Since a reinstall fixed the issue, I'm closing this bug.
