### ISSUE TITLE
Not able to send funds after a reorg

### ISSUE THREAD

**Issue by TurquoiseJay** [hhanh00/zwallet#79]
### Subject of the issue
When a reorg occurs while Ywallet is open (after in-app notification appears)

![reorg](https://user-images.githubusercontent.com/122416095/232942392-8d6df82d-4394-4776-a7fb-80262e0349c3.jpg)

 its not possible to send ZEC. 

When trying to create a transaction an error message appears: Not enough funds: Missing [in this case 800000] zats

<img src=https://user-images.githubusercontent.com/122416095/232942541-345ea332-a4a7-4466-94f0-46f38143ade1.jpg width="340" height="90" />

### Your environment
* Ywallet 1.3.6+427
* Android 11

### Steps to reproduce
1. Open app
2. Wait for reorg with the app open
3. Create a transaction
5. Tap send
6. '' Not enough funds: Missing [XXXXXXXX] zats '' error will appear

### Expected behaviour
Automatically rewind to 1 block before reorg and rescan

### Actual behaviour
Ywallet doesnt automatically rewind to before the reorg and must be done manually via the rewind checkpoint tool.

Note: After manually rewinding to the checkpoint before reorg the transaction appears to have been successfully broadcast and confirmed.

**Comment by hhanh00** [comment]
Your qr code cannot be read by qr droid either. It looks like something is wrong with it.
