### ISSUE TITLE
App crashes after clicking "send" button

### ISSUE THREAD

**Issue by rcz0** [hhanh00/zwallet#81]
### Subject of the issue
The app crashes (closes) after clicking "send" button

### Your environment
* v1.4.0 pre-release (.AppImage)
* Ubuntu 22.10
* Wallet with 2 ZEC Orchard accounts (1 main + 1 imported from Ledger S+ following the last available instructions)

### Steps to reproduce
All tried "send" transactions produced a crash of the app, but with different results : 
1) Transaction "Main account to Ledger account" produces a crash but the transaction is executed successfully on the blockchain (the crash occurs just after the window with message "Payment in progress" appears.
2) Transaction "Ledger account to Main account" crashes the app before anything is asked from the Ledger device. The transaction is not executed on the blockchain.

### Expected behaviour
Obvious

### Actual behaviour
So with this setup it is possible to receive ZEC on a Ledger account, but not possible to send ZEC from it.

**Comment by hhanh00** [comment]
Does it work when you transfer from a regular account to another regular
account?

**Comment by rcz0** [comment]
No, it crashes too. (But the transaction is executed on the blockchain.)

**Comment by rcz0** [comment]
Yes, it can. No sound at all (from regular account to regular account).

**Comment by hhanh00** [comment]
There is a problem with playing sounds from the app image then.

There is a new version that let's you turn sounds off.

https://github.com/hhanh00/zwallet/actions/runs/4881030097

**Comment by rcz0** [comment]
With this new version, removing the "Play Sound" option does solve the problem for regular transactions.
But trying to send from the Ledger account still causes a crash of the app. However the process now goes one step further : after pressing the "Send" button, the Ledger displays "calculating the o-key" for some time and then the app crashes.

**Comment by rcz0** [comment]
The ledger app installed was the one from yesterday morning. It seems it is not the same as one available now.
With the new ledger app, the problem is solved : the send transaction from Ledger is successful without crash :)

However, the installation of the new ledger app (over the old one) has generated a new UA address...is it possible to retrieve the address of the previous ledger app with the new ledger app ? Maybe it is a question for another thread ?

**Comment by hhanh00** [comment]
It is possible but unless it is a significant amount of funds, I'd just
forget about it. Alternatively, you can email me the seed phrase (if it is
not used for anything else) and I'll get it back to you.

**Comment by rcz0** [comment]
It is a small amount, no worry :)
