### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Arinababarina** [hhanh00/zwallet#82]
### Subject of the issue
Describe your issue here.
sent money from one wallet to another ,but they didn't get to
fe0822372e04daf31aff0b98d9a86dc85b2c8b07126649fe29041c3227880c8e
u19ywpcvzae2zkwzkg36rxeh648t8sd5cvn3r5372den8kej0rpgssr9gzx3feqamg92fzjv98s05q9n7erspajasecy447w6s9v30h0w2
should have come here
u1edf7vxxfaxzdsu8qt5rdcmc7hqx88kw34jh9qdzmrpfugnsvrs446j4s8wzgejfz9gsuf0zwnsxpruc8ymjphf889ze3xnc9j97tlsq9v3fyl4k5apvfvu97hy3a2llxfl47uupjwy052s4auelw0dsrzacdcsvnmrael07zkwgv2e2ks4mvkxs3rqe6ehrae7qus5vt8wlmvmcw63f
![Screenshot_20230507_002552_Zecwallet Lite](https://user-images.githubusercontent.com/132782543/236643159-1101dd7b-1302-4d3b-bc16-613bbdfea8e3.jpg)

### Your environment
* version of YWallet
* platform and version. Ex: Android 11, Windows 10, etc.
* if you were upgrading, the previous version you had

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a minimal reproducible scenario.
If possible, do a screen recording

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by hhanh00** [comment]
This is not ywallet. You are using zecwallet.
