### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by conradoplg** [hhanh00/zwallet#83]
What is the YWallet license? From https://github.com/hhanh00/zwallet/blob/95dfe035b9ef14d54d666cdb8a98a0dec2a8f3a5/misc/PKGBUILD it seems it's MIT, but it would be good to have a `LICENSE` file to make it clear for people wanting to contribute or use the code. Thanks!

**Comment by hhanh00** [comment]
https://forum.zcashcommunity.com/t/ywallet-maintenance-and-minor-improvements/45041/3?u=hanh
