### ISSUE TITLE
AppImage fails with undefined symbol error: wl_proxy_marshal_flags

### ISSUE THREAD

**Issue by gasull** [hhanh00/zwallet#84]
### Subject of the issue
`AppImage` doesn't work.

### Your environment
* version of YWallet: v1.4.0
* platform and version. Linux
* if you were upgrading, the previous version you had
Not upgrading.

### Steps to reproduce
Download latest AppImage, try to run it.

### Expected behaviour
YWallet should run.

### Actual behaviour
```
/tmp/.mount_YwallepCCLOK/ywallet: symbol lookup error: /tmp/.mount_YwallepCCLOK/usr/lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: wl_proxy_marshal_flags
```

**Comment by hhanh00** [comment]
All the system libraries are not bundled in the AppImage. Gtk should be present on your system. I don't think this error is related specifically to YWallet therefore you'd better search for `wl_proxy_marshal_flags`

**Comment by gasull** [comment]
That's not obvious and should be stated in the README.  I sent PR #92.
