### ISSUE TITLE
Don't show balance in the same view as the receive QR code

### ISSUE THREAD

**Issue by bobanm** [hhanh00/zwallet#9]
The first thing is that showing balance on receive view is a privacy flaw. If I want someone to scan my code and send me ZEC, I don't want them to know my balance.

Furthermore the _Account_ tab already seems way too busy. It currently shows:
1. balance
2. receive address + QR code
3. send button

IMO, these 3 things deserve to be on 3 different tabs: _Balance_, _Send_ and _Receive_. That is quite common UX for mobile wallets. What's the point in showing only send button which opens a send dialog? I think it would be cleaner to introduce _Send_ tab, which would already contain the send form. It require the same amount of taps to navigate to, but provides much cleaner experience.

**Comment by bobanm** [comment]
Not sure what do you mean by "press the qr button next to the address".

1. Tapping on the QR code toggles between shielded and transparent addresses. It doesn't help if I want to received ZEC to my shielded address, or if I have a balance on the transparent address that is revealed.
2. Tapping on _New Snap Address_ button generates a new shielded address, but still shows my shielded balance.

**Comment by hhanh00** [comment]
Maybe you were not using a recent version, this issue was reported in the forums.

https://forum.zcashcommunity.com/t/zwallet-ywallet-testing-released/39673/164

**Comment by bobanm** [comment]
You're right. I was using the latest version available on Google Play Store [shows `1.0.9+85` in about dialog].

Now I downloaded the latest testnet version from GitHub release page [shows `1.0.9+114` on GitHub but `1.0.9+1112` in about dialog]. In that version there is indeed a small button to show QR code only 👍🏻
