### ISSUE TITLE
Stale address after clicking payment uri

### ISSUE THREAD

**Issue by skyl** [hhanh00/zwallet#90]
![Screenshot_20230619_214449_Discord](https://github.com/hhanh00/zwallet/assets/61438/50fbc469-2e1d-4f93-bdda-8a163057998a)

### Your environment
Android

![Screenshot_20230619_214738](https://github.com/hhanh00/zwallet/assets/61438/33df6e53-f804-46d6-a894-4985bdd63e2a)

**Comment by hhanh00** [comment]
I am not able to reproduce this bug yet.

**Comment by hhanh00** [comment]
Closed due to inactivity
