### ISSUE TITLE
Cannot pool transfer from orchard to transparent 

### ISSUE THREAD

**Issue by humanhorn** [hhanh00/zwallet#94]
### Subject of the issue
Tried to pool transfer zec from orchard pool to transparent pool, a transaction was completed and a fee was paid, but funds stayed in orchard pool

### Your environment
* version 1.3.6
* Android 13

### Steps to reproduce
Settings -> pool transfer ->
From pool -> orchard
To pool -> transparent
Amount not set to max
Include fee in amount not ticked
No memo
Max amount per note 0.000

Press transfer and the net orchard amount will be -0.00001 (ie just the fee)

### Expected behaviour
Funds move from orchard to transparent pools

### Actual behaviour
Funds stay in orchard after a transaction

**Comment by hhanh00** [comment]
That is fixed in the release 1.4.0 but it is not shipped for Android yet. Could you try on desktop?
