### ISSUE TITLE
Support connecting directly to local zcashd full node

### ISSUE THREAD

**Issue by metalworker2** [hhanh00/zwallet#96]
### Subject of the issue

I would like to use Ywallet by connecting directly to my own locally running zcashd node. I do not want to have to run both zcashd and lightwalletd when all the data I need is in zcashd. This will reduce resource requirements and make Ywallet easier to use with a local full node (which is needed for security and privacy).

**Comment by hhanh00** [comment]
The data is in zcashd but lightwalletd provides a "compact" data interface. Without it, a wallet would download the entire blockchain (with zkp, equihash, etc). That's 20x more data.
At this point, there is no plan to support connecting YWallet directly to zcashd.
