### ISSUE TITLE
Memo When Sending to T-address

### ISSUE THREAD

**Issue by davidheisenberg** [hhanh00/zwallet#99]
### Subject
There shouldn’t be a memo field when sending to a t-addr

### Your environment
* version of YWallet: 1.4.1
* platform and version. iOS 16.6

### Steps to reproduce
Sending single txn from Orchard to a t-addr. 

### My problem
Ywallet allows user to fill out a memo when sending to a t-addr, but t-addr can’t receive memos. This is confusing. Suggestion: have memo area be grayed out or disappear if recipient address is a t-addr.

**Comment by hhanh00** [comment]
The user is free to fill the form in any order. We let them enter a memo before the address. Therefore, we don't disable the memo field.

**Comment by davidheisenberg** [comment]
I would consider graying out the memo field if a t-addr is entered.
Allowing a user to take an action that they think is doing one thing
(including a memo to a t-addr recipient) while in reality not doing that
thing adds confusion and friction to an experience which is already
confusing to many users.
